[package]
name = "xrpl-rust"
version = "0.1.0"
edition = "2018"
authors = ["Tanveer Wahid <tan@wahid.email>"]
description = "A Rust library to interact with the XRPL"
readme = "../README.md"
license = "ISC License"
repository = "https://github.com/sephynox/xrpl-rust"

[package.metadata.release]
tag-name = "{{version}}"

[lib]
name = "xrpl"
crate-type = ["lib"]

[dependencies]
regex = { version = "1.5.4", default-features = false }
num-bigint = { version = "0.4.2", default-features = false }
hex = { version = "0.4.3", default-features = false, features = ["alloc"] }
chrono = { version = "0.4.19" }
rust_decimal = { version = "1.16.0", default-features = false }
bs58 = { version = "0.4.0", default-features = false, features = ["check", "alloc"] }
serde = { version = "1.0.130", default-features = false, features = ["derive"] }
serde_json = { version = "1.0.68", default-features = false, features = ["alloc"] }
strum = { version = "0.22.0" }
strum_macros = { version = "0.22.0" }
indexmap = { version = "1.7.0", features = ["serde"] }
lazy_static = "1.4.0"
sha2 = "0.9.8"
rand_hc = "0.3.1"
rand = { version = "0.8.4", default-features = false, features = ["getrandom"] }
ripemd160 = "0.9.1"
ed25519-dalek = "1.0.1"
secp256k1 = { version = "0.20.3", default-features = false, features = ["alloc"] }

[dev-dependencies]
criterion = "0.3.5"

[[bench]]
name = "benchmarks"
harness = false

[features]
default = []
std = [
    "rand/std", 
    "regex/std", 
    "num-bigint/std", 
    "rand/std_rng", 
    "hex/std", 
    "rust_decimal/std", 
    "bs58/std", 
    "serde/std", 
    "indexmap/std", 
    "secp256k1/std"
]
