[package]
name = "xrpl-rust"
version = "0.1.0"
edition = "2018"
authors = ["Tanveer Wahid <tan@wahid.email>"]
description = "A Rust library to interact with the XRPL"
readme = "../README.md"
license = "ISC License"
repository = "https://github.com/sephynox/xrpl-rust"

[lib]
name = "xrpl_rust"
crate-type = ["staticlib", "cdylib"]

[dependencies]
hex = { version = "0.4.3", default-features = false }
chrono = { version = "0.4.19" }
rust_decimal = { version = "1.16.0", default-features = false }
bs58 = { version = "0.4.0", default-features = false }
strum = { version = "0.21.0" }
strum_macros = { version = "0.21.1" }

[features]
default = ["std", "bs58/check"]
std = ["hex/std", "rust_decimal/std", "bs58/std"]
