[package]
name = "xrpl-rust"
version = "0.1.0"
edition = "2018"
authors = ["Tanveer Wahid <tan@wahid.email>"]
description = "A 100% Rust library to interact with the XRPL"
readme = "README.md"
license = "ISC License"
repository = "https://github.com/589labs/xrpl-rust"

keywords = ["xrpl", "no_std"]
categories = ["dlt", "api", "no-std"]

[package.metadata.release]
no-dev-version = true
tag-name = "{{version}}"

[lib]
name = "xrpl"
crate-type = ["lib"]

[dependencies]
lazy_static = "1.4.0"
sha2 = "0.9.8"
rand_hc = "0.3.1"
ripemd160 = "0.9.1"
ed25519-dalek = "1.0.1"
indexmap = { version = "1.7.0", features = ["serde"] }
strum = { version = "0.22.0", default-features = false }
strum_macros = { version = "0.22.0", default-features = false }
regex = { version = "1.5.4", default-features = false }
num-bigint = { version = "0.4.2", default-features = false }
rust_decimal = { version = "1.16.0", default-features = false, features = ["serde"] }
chrono = { version = "0.4.19", default-features = false, features = ["alloc", "clock"] }
hex = { version = "0.4.3", default-features = false, features = ["alloc"] }
bs58 = { version = "0.4.0", default-features = false, features = ["check", "alloc"] }
serde = { version = "1.0.130", default-features = false, features = ["derive"] }
serde_json = { version = "1.0.68", default-features = false, features = ["alloc"] }
rand = { version = "0.8.4", default-features = false, features = ["getrandom"] }
secp256k1 = { version = "0.20.3", default-features = false, features = ["alloc"] }

[dev-dependencies]
criterion = "0.3.5"
cargo-husky = { version = "1.5.0", default-features = false, features = ["user-hooks"] }

[[bench]]
name = "benchmarks"
harness = false

[features]
default = ["std", "core", "models", "utils"]
models = ["core"]
core = ["utils"]
utils = []
std = [
    "rand/std", 
    "regex/std",
    "chrono/std", 
    "num-bigint/std", 
    "rand/std_rng", 
    "hex/std", 
    "rust_decimal/std", 
    "bs58/std", 
    "serde/std", 
    "indexmap/std", 
    "secp256k1/std"
]
